import { mkdtemp, readFile, realpath } from "node:fs/promises";
import { tmpdir } from "node:os";
import { basename, dirname, isAbsolute, join, relative, resolve } from "node:path";
import { toolsFileSchema } from "@vendoai/actions";
import { vendoSync } from "@vendoai/actions/sync";
import { VENDO_POLICY_FORMAT, vendoThemeSchema } from "@vendoai/core";
import { toVendoTheme } from "../init.js";
import { readOptional, writeText } from "../shared.js";
import { extractTheme } from "../theme/extract-theme.js";

/**
 * The deterministic extraction pass behind `npx vendo try` (unified try
 * surface, Task 2): profile a host repo for the first paint with ZERO
 * commitment — no key, no network, no model, and above all no writes.
 *
 * The zero-commit contract: `repoRoot` is read-only, byte for byte. Every
 * artifact lands under `profileRoot` (a fresh `vendo-try-` temp dir when the
 * caller doesn't supply one), laid out exactly like a normal `.vendo/`
 * profile root so `assembleTryProfile(profileRoot)` (Task 1) boots from it
 * directly. A `profileRoot` inside `repoRoot` is refused outright — that
 * placement IS a write into the repo — with symlinks resolved on both sides
 * first, so a link cannot smuggle the profile back into the repo. The
 * returned `profileRoot` is caller-owned: this pass never deletes it, so a
 * temp dir it created leaks unless the caller removes it when done.
 *
 * Two existing extractors run, never reimplementations:
 *   - theme: `extractTheme` (exact-only allowlist pass), converted through
 *     init's own `toVendoTheme` → `.vendo/theme.json`
 *   - tools/catalog: `vendoSync` with `out` pointed at the profile root →
 *     `.vendo/tools.json`, `catalog.json`, ...
 *
 * Fail-soft like the assembler it feeds: either extractor throwing is
 * recorded in the summary (`status: "failed"`), never rethrown — the surface
 * must paint from whatever partial profile survived.
 */

export interface DeterministicPassOptions {
  /** The host repo to profile. Never written to. */
  repoRoot: string;
  /** Where artifacts land; a fresh temp dir is created when omitted. */
  profileRoot?: string;
}

export interface DeterministicPassResult {
  /** Caller-owned (never cleaned up here), whether supplied or freshly made. */
  profileRoot: string;
  /** slotsMatched counts exact allowlist reads plus their derived slots
   *  (contrast accentText, inherited headingFamily) — 0 = all-default theme;
   *  a carried-over host theme.json (below) reports its own top-level key
   *  count here instead — still ">0 = captured" for try.ts's summary line. */
  theme: { status: "written" | "failed"; slotsMatched: number; error?: string };
  /** A failed sync carries its error as a warning — same channel as sync's own. */
  tools: { status: "written" | "failed"; count: number; warnings: string[] };
  /** Caller-authored `.vendo/` INPUTS carried read-only from the host repo,
   *  never derived by this pass on its own: an existing artifact is the
   *  host's explicit choice and wins outright (theme.json over this pass's
   *  own extraction; brief.md/design-rules.md over the later AI deepening
   *  draft, which only drafts when absent). `policy` is the one exception —
   *  it is either carried from the host or a fresh honest demo policy is
   *  written (never left absent): a temp profile with no policy.json makes
   *  the guard report "unconfigured" and the surface nags with the
   *  "Vendo is running without a policy" banner for every session, not just
   *  the first paint. */
  carriedHostInputs: {
    theme: boolean;
    brief: boolean;
    designRules: boolean;
    policy: "carried" | "demo";
  };
}

/** The permissive policy this pass writes into the temp profile when the
 *  host repo carries none of its own: every risk auto-runs, matching the
 *  CURRENT unconfigured-guard fallthrough byte for byte (`packages/guard`'s
 *  `#pipeline` default is `{ action: "run", decidedBy: "default" }` with no
 *  policy configured at all) — this only changes the REPORTED posture from
 *  "unconfigured" to "rules" (silencing the nag banner), never what actually
 *  runs. `directions` carries the honest comment-equivalent marker JSON has
 *  no syntax for. */
const DEMO_POLICY = {
  format: VENDO_POLICY_FORMAT,
  directions: [
    "Auto-generated by `npx vendo try` — no .vendo/policy.json existed on this "
      + "host, and every action here runs against synthetic fixture data anyway, "
      + "so this demo policy runs everything without asking.",
  ],
  rules: [{ match: {}, action: "run" as const }],
};

/** Resolve symlinks through the nearest EXISTING ancestor, re-joining any
 *  not-yet-created tail; falls back to the lexical path when nothing on the
 *  way exists (the relative() guard then judges the lexical spelling). */
async function realpathToward(path: string): Promise<string> {
  let existing = path;
  const tail: string[] = [];
  for (;;) {
    try {
      return join(await realpath(existing), ...tail);
    } catch {
      const parent = dirname(existing);
      if (parent === existing) return path;
      tail.unshift(basename(existing));
      existing = parent;
    }
  }
}

/** Run the deterministic extractors against `repoRoot`, writing a paintable
 *  profile under `profileRoot`. Resolves (never rejects) for any readable
 *  repo; only the zero-commit placement guard throws. */
export async function runDeterministicPass(
  options: DeterministicPassOptions,
): Promise<DeterministicPassResult> {
  const repoRoot = resolve(options.repoRoot);
  const profileRoot = options.profileRoot === undefined
    ? await mkdtemp(join(tmpdir(), "vendo-try-"))
    : resolve(options.profileRoot);
  const placement = relative(await realpathToward(repoRoot), await realpathToward(profileRoot));
  if (placement === "" || (!placement.startsWith("..") && !isAbsolute(placement))) {
    throw new Error(`profileRoot ${profileRoot} is inside repoRoot ${repoRoot} — the try pass never writes into the repo`);
  }
  const vendoDir = join(profileRoot, ".vendo");
  const hostVendoDir = join(repoRoot, ".vendo");

  // Carry over caller-authored `.vendo/` INPUTS before anything else derives
  // its own defaults — read-only reads off repoRoot, writes only under
  // profileRoot (the zero-commit contract above holds: repoRoot never sees a
  // byte). theme.json below checks `hostTheme` FIRST and skips extraction
  // entirely when it's present, so the host's explicit theme always wins.
  const hostTheme = await readOptional(join(hostVendoDir, "theme.json"));
  const hostBrief = await readOptional(join(hostVendoDir, "brief.md"));
  const hostDesignRules = await readOptional(join(hostVendoDir, "design-rules.md"));
  const hostPolicy = await readOptional(join(hostVendoDir, "policy.json"));

  // Fail-soft like every other artifact in this pass (theme/tools below): a
  // profileRoot that can't be written to degrades this carry-over quietly
  // instead of throwing — the surface still paints from whatever landed.
  let briefCarried = false;
  let designRulesCarried = false;
  let policyCarried = false;
  try {
    if (hostBrief !== null) {
      await writeText(join(vendoDir, "brief.md"), hostBrief);
      briefCarried = true;
    }
    if (hostDesignRules !== null) {
      await writeText(join(vendoDir, "design-rules.md"), hostDesignRules);
      designRulesCarried = true;
    }
    await writeText(
      join(vendoDir, "policy.json"),
      hostPolicy ?? `${JSON.stringify(DEMO_POLICY, null, 2)}\n`,
    );
    policyCarried = true;
  } catch {
    // Degraded profileRoot: the theme/tools passes below hit the identical
    // failure and report it in their own summaries; this carry-over just
    // leaves its artifacts absent rather than throwing a second time.
  }

  let theme: DeterministicPassResult["theme"];
  if (hostTheme !== null) {
    try {
      const parsed = vendoThemeSchema.parse(JSON.parse(hostTheme));
      await writeText(join(vendoDir, "theme.json"), `${JSON.stringify(parsed, null, 2)}\n`);
      theme = { status: "written", slotsMatched: Object.keys(parsed).length };
    } catch (error) {
      theme = { status: "failed", slotsMatched: 0, error: String(error) };
    }
  } else {
    try {
      const summary = await extractTheme(repoRoot);
      await writeText(join(vendoDir, "theme.json"), `${JSON.stringify(toVendoTheme(summary.slots), null, 2)}\n`);
      theme = { status: "written", slotsMatched: Object.keys(summary.matched).length };
    } catch (error) {
      theme = { status: "failed", slotsMatched: 0, error: String(error) };
    }
  }

  let tools: DeterministicPassResult["tools"];
  try {
    const report = await vendoSync({ root: repoRoot, out: vendoDir });
    const written = toolsFileSchema.parse(JSON.parse(await readFile(join(vendoDir, "tools.json"), "utf8")));
    tools = { status: "written", count: written.tools.length, warnings: report.warnings };
  } catch (error) {
    tools = { status: "failed", count: 0, warnings: [String(error)] };
  }

  return {
    profileRoot,
    theme,
    tools,
    carriedHostInputs: {
      theme: hostTheme !== null && theme.status === "written",
      brief: briefCarried,
      designRules: designRulesCarried,
      policy: hostPolicy !== null ? "carried" : "demo",
    },
  };
}
